site_name: Aktindo's Projects
theme:
  name: material
  favicon: assets/code-solid.svg
  icon:
    logo: fontawesome/solid/code
    repo: fontawesome/brands/git-alt
  palette:
    primary: indigo
  features:
    - navigation.instant
  nav:
    - Section:
      - setup/index.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aktindo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aktindo
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6g297Usrsn
copyright: Copyright &copy; 2020-2021 Aktindo
markdown_extensions:
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
repo_url: https://github.com/Aktindo/Project-Docs
repo_name: Aktindo/Project-Docs
edit_uri: edit/main/docs/
plugins:
  - git-revision-date-localized:
      type: timeago